version: "3"
services:
    backend:
        container_name: qr_reader_bot
        restart: always
        build: ./
        environment:
            - "BOT_TOKEN=${BOT_TOKEN}"
            - "NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}"
